demo/index.html, src/api-viewer-demo-layout.ts, src/api-viewer-docs.ts, src/api-viewer-styles.ts, src/fixtures/expansion-panel.ts, src/lib/knobs.ts, src/lib/renderer.ts, src/lib/types.ts, src/lib/utils.ts
Fixes #17 
Decided to exclude multi-select knob (checkbox group) for now due to complexity it brings.
Using `string` knob should be enough to make it possible to set `theme` attribute value.
Will reconsider an option to add multi-select knob support in future.
=> Add string, boolean and select custom knobs

demo/index.html, src/api-demo-base.ts, src/api-demo-content.ts, src/api-demo-styles.ts, src/api-demo.ts, src/api-docs-base.ts, src/api-docs-content.ts, src/api-docs-styles.ts, src/api-docs.ts, src/api-viewer-base.ts, src/api-viewer-content.ts, src/api-viewer-mixin.ts, src/api-viewer-styles.ts, src/shared-styles.ts
Fixes #14 
From now on, there will be 3 options:
- `<api-viewer>` - docs + demo
- `<api-docs>` - docs only
- `<api-demo>` - demo only
=> Add separate docs and demo components

src/api-demo-knobs-mixin.ts, src/api-demo-layout-mixin.ts, src/api-viewer-demo.ts, src/lib/demo-snippet.ts, src/lib/knobs.ts, src/lib/renderer.ts, src/lib/types.ts, src/lib/utils.ts
Ported some changes from #84 and adapted to the current implementation, to make adding CEM easier.
=> refactor: update knobs types, simplify logic

src/api-demo-knobs-mixin.ts, src/api-viewer-demo.ts, src/controllers/slots-controller.ts, src/lib/renderer.ts
Follow-up from #91 but for slots. This also helps to make `renderer` directive slightly cleaner.
=> refactor: split slots logic to controller

src/api-demo-knobs-mixin.ts, src/api-viewer-demo.ts, src/controllers/styles-controller.ts, src/lib/renderer.ts
Follow-up from #93 but for custom CSS properties. This also helps to make `renderer` directive smaller.
=> refactor: split styles logic to controller

CODE_OF_CONDUCT.md, CONTRIBUTING.md
These are copied from the Modern Web repo, with a few "Contributing" parts removed (namely tests and changesets).
=> chore: add code of conduct and contributing guide

src/lib/renderer.ts
For some reason, in certain cases setting `opened` to true using knob was only setting the attribute.
Now when I'm looking at the code, I see no reason to prefer attribute in the demo renderer.
=> fix: set boolean knob value using property

docs/_assets/home.css
Changed to use a breakpoint for the reasons block to make the home page responsive.
=> docs: prevent horizontal scroll on mobile

docs/docs/api/index.md, docs/docs/examples/index.md, docs/docs/guide/index.md
The categories `index` pages were missing links to their content articles, this is now fixed.
=> docs: add missing links to categories pages

package.json, yarn.lock
Looks like these version bumps do not break anything in the docs site, so we can use them.
=> chore: use resolutions to fix audit warnings

docs/docs/api/styling.md, src/api-demo-base.ts, src/api-docs-base.ts, src/api-viewer-base.ts
For some reason, these container elements were not exposed as stylable shadow parts. This PR fixes that.
=> feat: add shadow parts for container elements

docs/docs/api/elements.md, docs/docs/api/templates.md, docs/docs/guide/using-demo.md
Added some links between different docs pages to make navigation easier. Also, improved wording a bit.
=> docs: add cross-references, minor improvements

README.md
As the API documentation has been moved to the new website, there is no more need to have it in the README.
=> docs: cleanup README, add links to docs pages

src/api-viewer-demo.ts
Copied the corresponding code from `api-viewer-docs` to reset the tab when changing the selected element.
=> fix: reset selected tab when element changes

src/api-viewer-tabs.ts
There was an error when switching from an element not having any API to the other one that does have API.
This workaround prevents an error from being thrown. I will try to come up with a better fix later.
=> fix: do now throw when panel does not exist

src/lib/demo-snippet.ts, src/lib/highlight-css.ts
This caused the `size-limit` to fail, and in general we need `.js` extensions when using ES modules.
=> fix: add missing .js extension to imports

src/lib/manifest.ts
This is an extract from my `custom-elements.json`
```json
{
"kind": "javascript-module",
"path": "mdjs-layout/define.js",
"declarations": [],
"exports": [
{
"kind": "custom-element-definition",
"name": "mdjs-layout",
"declaration": {
"name": "MdjsLayout",
"module": "/mdjs-layout/src/mdjs-layout.ts"
}
}
]
},
...
{
"kind": "javascript-module",
"path": "mdjs-layout/src/mdjs-layout.ts",
"declarations": [
{
"kind": "class",
"description": "",
"name": "MdjsLayout",
"members": [
```
Since the export module has a leading slash, while the path doesn't, it's not found
```
"module": "/mdjs-layout/src/mdjs-layout.ts"
"path": "mdjs-layout/src/mdjs-layout.ts",
```
I think it's correct to assume that if the `module` path starts with a leading slash, it refers to a root path, so we can remove it while …
=> fix: root path lookup

docs/docs/api/styling.md, src/api-viewer-tab.ts, src/styles/shared-styles.ts
Currently I can't set the header background without breaking the selected tab color A11Y, because both are controlled by the same `--ave-primary-color`.
I suggest to keep `--ave-primary-color` as a default (also for backwards compatibility), but provide 2 new separate CSS custom props to customize the header and selected tab colors separately from it.
=> feat: allow styling header and selected tab color separately from primary

src/api-viewer-tabs.ts
Fixes this small overflow issue:
Fix is implemented in such a way that the situation with more content is covered too:
=> fix: selected tab border radius

CONTRIBUTING.md, LICENSE.md, README.md, docs/_data/footer.json, docs/_data/site.cjs, docs/docs/api/templates.md, docs/docs/guide/writing-jsdoc.md, package.json
The repository has been transferred under https://github.com/open-wc organization.
=> chore: rebrand repository under open-wc

package.json
Changed `"author"` to `open-wc` and aligned `"contributors"` field with the format recommended by npm:
https://docs.npmjs.com/cli/v8/configuring-npm/package-json#people-fields-author-contributors
=> chore: update author and contributors

.changeset/gorgeous-trees-smash.md, packages/api-demo/src/controllers/abstract-controller.ts, packages/api-demo/src/controllers/events-controller.ts, packages/api-demo/src/controllers/slots-controller.ts, packages/api-demo/src/controllers/styles-controller.ts, packages/api-demo/src/layout.ts
Removed incorrect `hostDisconnected` callbacks which caused state to be reset when switching from demo to docs and back (as a result, code snippet for `expansion-panel` was rendering incorrectly in this case).
=> fix: improve demo controllers, do not reset state

.changeset/neat-poets-thank.md, packages/api-common/src/manifest.ts, packages/api-demo/src/controllers/events-controller.ts, packages/api-demo/src/controllers/slots-controller.ts, packages/api-demo/src/controllers/styles-controller.ts, packages/api-demo/src/layout.ts, packages/api-demo/src/types.ts, packages/api-demo/src/ui/controls.ts, packages/api-demo/src/ui/events.ts, packages/api-demo/src/ui/knobs.ts, packages/api-demo/src/ui/renderer.ts, packages/api-demo/src/ui/snippet.ts
Moved some types to `api-demo` package. Also, created `types.ts` entrypoint to simplify imports.
=> refactor!: move demo types to api-demo package

.changeset/fifty-toes-confess.md, .eslintrc.json, packages/api-common/src/utils.ts, packages/api-demo/src/layout.ts, packages/api-docs/src/layout.ts, packages/api-tabs/package.json, packages/api-tabs/src/api-viewer-panel.ts, packages/api-tabs/src/api-viewer-tab.ts, packages/api-tabs/src/api-viewer-tabs.ts, packages/api-tabs/tsconfig.json
Updated `@api-viewer/tabs` package to use vanilla custom elements without `lit` and `tslib` dependencies.
=> refactor: use vanilla custom elements for tabs

.changeset/smooth-avocados-move.md, docs/assets/custom-elements.json, fixtures/lit/src/expansion-panel.ts, fixtures/lit/src/opened-mixin.ts, packages/api-common/src/manifest.ts, packages/api-docs/src/base.ts, packages/api-docs/src/layout.ts, packages/api-viewer/src/base.ts
Added basic support for methods. Currently, only name and description are shown.
Methods arguments and return type will be covered in a separate PR.
Related to #47
=> feat: add methods tab to API documentation

.changeset/fast-candles-beam.md, docs/assets/custom-elements.json, docs/docs/api/styling.md, fixtures/lit/src/progress-bar.ts, packages/api-common/src/shared-styles.ts, packages/api-docs/src/layout.ts, packages/api-docs/src/styles.ts, packages/api-viewer/package.json
Fixes #47
Here is how the method params and type look like:
=> feat: show method params and return type

.changeset/rare-numbers-hide.md, docs/docs/api/properties.md, packages/api-common/src/manifest-mixin.ts, packages/api-common/src/manifest.ts, packages/api-demo/src/base.ts, packages/api-docs/src/base.ts, packages/api-viewer/package.json, packages/api-viewer/src/base.ts
This is another angle of how `api-viewer` can be used, instead of providing a full API of all components in a single place it can be used on specific doc pages and only show specific component API.
To achieve that goal this PR adds `only` property to filter elements in such a way that only the listed elements remain.
If `only` contains one element name, then it will display only the API of that element without the selector in top-right corner (no change here, it's already the behavior that the selector is hidden automatically if there is only one element), e.g.:
```markdown
...explain how to setup my-button component...
<api-docs src="/assets/custom-elements.json" only="my-button"></api-docs>
...mdjs demos...
```
Sometimes can be 2 components or more (comma-separated), e.g. do/dont …
=> feat: add only property to filter elements

.changeset/wicked-lizards-mate.md, packages/api-common/src/manifest.ts, packages/api-demo/src/base.ts, packages/api-docs/src/base.ts, packages/api-viewer/src/base.ts
Turned out there was a bug and filtered elements were not respected in `getElementData`, resulting in a first element in the original manifest to take priority over the first in the filtered array.
This PR should fix that.
PS:  I tested this behavior in #153, but maybe not correctly prepared the build and tested partially old code. I thought `yarn fixtures`, `yarn build` and then `yarn start` was a way to go, also tried to keep `yarn dev` and `yarn start` running side by side, but smth went wrong apparently resulting in this bug unnoticed. Maybe it's good to document in Contribution Guidelines how to properly work in a dev mode and always serve new version of the lib in the Rocket site.
=> fix: respect filtered elements when determining selected

.gitignore, package.json, yarn.lock
Fixes #157
Changed npm scripts to use https://github.com/google/wireit.
=> chore: use wireit for managing npm scripts

packages/api-demo/src/layout.ts
Refactored logic to fix the following error reported by the latest version of `eslint-plugin-lit`:
```
packages/api-demo/src/layout.ts
78:7  error  Members of `this` should not be assigned to in the render method. It is likely you should do this elsewhere instead (e.g. in `updated`)  lit/no-this-assign-in-render
```
=> refactor: move customElements.whenDefined to willUpdate

package.json, yarn.lock
Updating to `wireit` was not enough to fix the file changes problem reported in #157. 
This PR actually fixes it by using plain `tsc --build --watch` instead of `tsc-watch`.
=> chore: replace usage of tsc-watch with plain tsc

package.json, yarn.lock
Updated `lit-analyzer` version to `next`, see https://www.npmjs.com/package/lit-analyzer?activeTab=versions.
=> chore: update lit-analyzer to latest pre-release

scripts/generate-ts-configs.js, scripts/runWorkspacesScripts.js
In the upcoming PR the repo will be switched to use `eslint-config-vaadin` and this is a preparation step.
With type checking enabled, there were some errors reported for JS files in `scripts`. This PR fixes them.
=> chore: fix ESLint errors and use types in scripts

packages/api-demo/src/layout.ts
Fixed a regression from #172 that slipped in unnoticed. Not adding a changeset since it wasn't released.
=> fix: restore correct logic to sync knob on event

.changeset/fresh-candles-rush.md, docs/assets/custom-elements.json, package.json, packages/api-common/package.json, packages/api-common/src/manifest.ts, packages/api-demo/src/layout.ts, packages/api-demo/src/ui/knobs.ts, yarn.lock
We finally have `readonly` property standardized and can get rid of the workaround:
- https://github.com/webcomponents/custom-elements-manifest/pull/118
- https://github.com/open-wc/custom-elements-manifest/pull/203
Note, `custom-elements-manifest` needs a release so I had to add a workardound.
=> feat: update custom-elements-manifest to v2.0.0, add readonly

.stylelintrc, package.json, yarn.lock
- Removed [`stylelint-config-prettier`](https://www.npmjs.com/package/stylelint-config-prettier) as recommended when upgrading to Stylelint 15
- Upgraded `stylelint-config-standard` and changed [`media-feature-range-notation`](https://stylelint.io/user-guide/rules/media-feature-range-notation/)
=> chore: update stylelint-config-standard, remove some rules

.changeset/lazy-crabs-yell.md, docs/assets/custom-elements.json, docs/docs/api/styling.md, fixtures/lit/src/expansion-panel.ts, fixtures/lit/src/fancy-accordion.ts, fixtures/lit/src/intl-currency.ts, fixtures/lit/src/progress-bar.ts, packages/api-common/src/shared-styles.ts, packages/api-docs/src/layout.ts, packages/api-docs/src/styles.ts
This PR implements the feature described in https://github.com/open-wc/api-viewer-element/issues/151
=> feat: show whether the property is static

.changeset/old-days-kick.md, packages/api-common/src/manifest.ts, packages/api-docs/src/layout.ts
Shows whether a property is reflected. It's based on the changes in https://github.com/open-wc/api-viewer-element/pull/190 The important parts are in this commit: https://github.com/open-wc/api-viewer-element/commit/174b47a6f2715137aceb5d08cc0a25ca2a8d2e3d
I used the `CustomElementField` instead of the `ManifestClassField` because in the latter the `reflects` flag is not included. I'm not sure this is the right type but in fact, where I use this type the reflects flag is available. The result looks like this:
=> feat: support `reflects` flag

package.json, yarn.lock
For some reason, using `@lion/accordion` 0.11.1 breaks styles for accordions in `@mdjs/preview`. Let's downgrade it.
=> chore: downgrade lion-accordion to make preview styles work

.github/workflows/release.yml, .github/workflows/verify.yml
Updated `actions/checkout` and `actions/setup-node` to latest, changed Node version from 16 to 20.
=> chore: update GitHub Actions to latest, use Node 20

CONTRIBUTING.md
The `web` is a wrong folder name which is a leftover from the [original file](https://github.com/modernweb-dev/web/blob/master/CONTRIBUTING.md).
=> chore: fix copy-paste leftover in the contributing guide
