open-wc/api-viewer-element

README.md
src/api-viewer.ts

Expose section as a public property

---

README.md
src/api-viewer-select.ts
src/api-viewer.ts

Expose selected as a public property

---

README.md
src/@types/marked.esm.d.ts
src/lib/markdown.ts

Add parts attributes to docs markdown

---

README.md
src/api-viewer-base.ts
src/api-viewer-content.ts
src/api-viewer-demo-layout.ts
src/api-viewer-demo.ts

Add exclude-knobs attribute for demo

---

README.md
src/api-viewer-base.ts

Add elements property to pass data directly

---

src/api-viewer-base.ts
src/api-viewer-content.ts
src/api-viewer-demo-layout.ts
src/api-viewer-demo-snippet.ts
src/api-viewer-demo.ts
src/lib/renderer.ts
src/lib/utils.ts

Fix template data-target handling

---

demo/custom-elements.json
demo/index.html
src/api-viewer-demo-layout.ts
src/api-viewer-demo-snippet.ts
src/fixtures/intl-currency.ts
src/lib/renderer.ts
src/lib/utils.ts

Add prefix, suffix and wrapper templates

---

demo/custom-elements.json
package.json
src/api-viewer-demo-layout.ts
src/api-viewer-demo-snippet.ts
src/api-viewer-docs.ts
src/api-viewer-styles.ts
src/fixtures/expansion-panel.ts
src/fixtures/progress-bar.ts
src/lib/renderer.ts
src/lib/types.ts
src/lib/utils.ts
yarn.lock

Add CSS custom property type and default

---

src/api-viewer-demo-snippet.ts
src/lib/renderer.ts

Do not use div for the default slot

---

src/api-demo-knobs-mixin.ts
src/api-viewer-demo.ts

Moved some logic out of `ApiDemoKnobsMixin` to reduce its complexity and have all the events code in one place.

refactor: move events logic from KnobsMixin

---

src/api-demo-knobs-mixin.ts
src/api-viewer-demo.ts
src/controllers/events-controller.ts

This is a first step towards restructuring code using Lit controllers, to make it more readable and not so tied to Lit.

refactor: split events logic to controller

---

package.json

First step towards getting a documentation based on Rocket, added to mention in the release notes.

chore: add type and engines to package.json

---

docs/_assets/theme.css

Changed a few colors so they look brighter, to update the docs website look and feel.

docs: update buttons and links color theme

---

package.json
rocket.config.js
yarn.lock

I removed these parts of the Rocket config when creating the initial version of docs. Added them back now.

docs: add Rocket search preset, watch CSS files

---

docs/docs/guide/intro.md

As mentioned in https://github.com/web-padawan/api-viewer-element/issues/118#issuecomment-989609881, the current example is incorrect.

docs: update analyzer snippet to use globs

---

.changeset/nice-brooms-tell.md
packages/api-demo/src/controllers/slots-controller.ts
packages/api-demo/src/types.ts
packages/api-demo/src/ui/controls.ts

Fixed the slot knobs logic that I messed up that during monorepo conversion and forgot to fix yesterday.

fix: update slot knobs to render name properly

---

README.md

Updated and extended "Acknowledgements" section in README to pay tribute to CEM and Rocket authors 👏

chore: update Acknowledgements in README

---

.changeset/metal-games-tie.md
packages/api-common/src/shared-styles.ts

Added colors to provide nice default appearance when dark mode is preferred.

fix: adjust colors for dark color scheme

---

.github/workflows/release.yml
.github/workflows/verify.yml

Updated `actions/checkout` and `actions/setup-node` to latest version.

chore: update GitHub Actions to latest version

---

fixtures/lit/src/expansion-panel.ts
fixtures/lit/src/fancy-accordion.ts
fixtures/lit/src/intl-currency.ts
fixtures/lit/src/opened-mixin.ts
fixtures/lit/src/progress-bar.ts
packages/api-common/src/manifest-mixin.ts
packages/api-common/src/manifest.ts
packages/api-common/src/templates.ts
packages/api-common/src/utils.ts
packages/api-demo/src/api-demo.ts
packages/api-demo/src/base.ts
packages/api-demo/src/controllers/abstract-controller.ts
packages/api-demo/src/controllers/events-controller.ts
packages/api-demo/src/controllers/slots-controller.ts
packages/api-demo/src/controllers/styles-controller.ts
packages/api-demo/src/layout.ts
packages/api-demo/src/types.ts
packages/api-demo/src/ui/controls.ts
packages/api-demo/src/ui/events.ts
packages/api-demo/src/ui/highlight-css.ts
packages/api-demo/src/ui/knobs.ts
packages/api-demo/src/ui/renderer.ts
packages/api-demo/src/ui/snippet.ts
packages/api-docs/src/api-docs.ts
packages/api-docs/src/base.ts
packages/api-docs/src/layout.ts
packages/api-docs/src/utils/markdown.ts
packages/api-tabs/src/api-viewer-tabs.ts
packages/api-viewer/src/api-viewer.ts
packages/api-viewer/src/base.ts

This PR includes a bunch of small changes to address issues reported by `eslint-config-vaadin`.
Decided to split these into separate PR to keep the diff in the actual update PR smaller.

refactor: fix some issues found by using eslint-config-vaadin

---

package.json
yarn.lock

Updated Rocket and Lion web components to match versions at https://github.com/modernweb-dev/web/commit/7023c3d11238f2aa21e3d36674e4d455f02febad

chore: update Rocket and Lion web components

---

.changeset/warm-mails-fry.md
packages/api-demo/src/styles.ts

fix: use proper selector for api-demo copy button styles
